import type { GeneratedProjectResponse } from "@/types/projectCode";

// ──────────────────────────────────────────────
// Mock data – mirrors a realistic generated project
// ──────────────────────────────────────────────
const MOCK_PROJECT: GeneratedProjectResponse = {
  projectId: "demo",
  files: [
    {
      path: "src/pages/Home.tsx",
      language: "tsx",
      content: `import React from 'react';
import { Hero } from '../components/Hero';
import { Header } from '../components/Header';

export default function Home() {
  return (
    <div className="min-h-screen bg-background">
      <Header />
      <Hero />
      <main className="container mx-auto px-4 py-12">
        <h2 className="text-3xl font-bold mb-6">
          Welcome to Your App
        </h2>
        <p className="text-muted-foreground leading-relaxed">
          This is the main landing page of your
          generated application.
        </p>
      </main>
    </div>
  );
}`,
    },
    {
      path: "src/pages/About.tsx",
      language: "tsx",
      content: `import React from 'react';

export default function About() {
  return (
    <div className="container mx-auto px-4 py-12">
      <h1 className="text-4xl font-bold mb-4">About Us</h1>
      <p className="text-muted-foreground">
        Learn more about our mission and team.
      </p>
    </div>
  );
}`,
    },
    {
      path: "src/pages/Pricing.tsx",
      language: "tsx",
      content: `import React from 'react';

export default function Pricing() {
  return (
    <div className="container mx-auto px-4 py-12">
      <h1 className="text-4xl font-bold mb-4">Pricing</h1>
      <div className="grid grid-cols-3 gap-6">
        <PriceCard title="Free" price="$0" />
        <PriceCard title="Pro" price="$19" />
        <PriceCard title="Enterprise" price="$99" />
      </div>
    </div>
  );
}`,
    },
    {
      path: "src/components/Header.tsx",
      language: "tsx",
      content: `import React from 'react';
import { Link } from 'react-router-dom';

export function Header() {
  return (
    <header className="border-b border-border">
      <nav className="container mx-auto px-4 h-16
        flex items-center justify-between">
        <Link to="/" className="text-xl font-bold">
          MyApp
        </Link>
        <div className="flex gap-6">
          <Link to="/about">About</Link>
          <Link to="/pricing">Pricing</Link>
        </div>
      </nav>
    </header>
  );
}`,
    },
    {
      path: "src/components/Hero.tsx",
      language: "tsx",
      content: `import React from 'react';

export function Hero() {
  return (
    <section className="py-24 text-center">
      <h1 className="text-5xl font-bold mb-4">
        Build Something Amazing
      </h1>
      <p className="text-xl text-muted-foreground">
        Get started with your next project today.
      </p>
    </section>
  );
}`,
    },
    {
      path: "src/styles/index.css",
      language: "css",
      content: `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --background: 0 0% 100%;
  --foreground: 240 10% 3.9%;
  --primary: 174 100% 45%;
}`,
    },
    {
      path: "package.json",
      language: "json",
      content: `{
  "name": "my-generated-app",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-router-dom": "^6.30.1"
  }
}`,
    },
    {
      path: "README.md",
      language: "markdown",
      content: `# My Generated App

This project was generated by MyCodex.Dev.

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`

## Project Structure

- \`src/pages/\` — Route pages
- \`src/components/\` — Reusable UI components
- \`src/styles/\` — Global stylesheets
`,
    },
  ],
};

/**
 * Fetch generated project files.
 *
 * TODO: Replace mock with real API call:
 *   const res = await fetch(\`/api/projects/\${projectId}/code\`);
 *   return res.json() as GeneratedProjectResponse;
 */
export async function fetchGeneratedProject(
  projectId: string
): Promise<GeneratedProjectResponse> {
  // Simulate network latency
  await new Promise((r) => setTimeout(r, 600));
  return { ...MOCK_PROJECT, projectId };
}
